---
service_user: "{{ wso2_service_user }}"

# Database settings
is_identity_db_host: "{{ mysql_host | default('localhost') }}"
is_identity_db_port: "{{ mysql_port | default(3306) }}"
is_identity_db_name: "{{ mysql_is_db | default('wso2_is_db') }}"
is_identity_db_username: "{{ mysql_user | default('nemis') }}"
is_identity_db_password: "{{ mysql_password | default('nemis1234') }}"

is_shared_db_host: "{{ mysql_host | default('localhost') }}"
is_shared_db_port: "{{ mysql_port | default(3306) }}"
is_shared_db_name: "{{ mysql_is_shared_db | default('wso2_is_shared_db') }}"
is_shared_db_username: "{{ mysql_user | default('nemis') }}"
is_shared_db_password: "{{ mysql_password | default('nemis1234') }}"

# Server settings
is_server_hostname: "{{ is_hostname | default('localhost') }}"
is_server_base_path: "https://{{ is_server_hostname }}"

# APIM connection (for event listener notification)
apim_server_host: "{{ apim_host | default('localhost') }}"
apim_server_port: "{{ apim_port | default('9443') }}"
