---
service_user: "{{ wso2_service_user }}"

# Database settings
apim_db_host: "{{ mysql_host | default('localhost') }}"
apim_db_port: "{{ mysql_port | default(3306) }}"
apim_db_name: "{{ mysql_apim_db | default('wso2_apim_db') }}"
apim_db_username: "{{ mysql_user | default('nemis') }}"
apim_db_password: "{{ mysql_password | default('nemis1234') }}"

apim_shared_db_host: "{{ mysql_host | default('localhost') }}"
apim_shared_db_port: "{{ mysql_port | default(3306) }}"
apim_shared_db_name: "{{ mysql_apim_shared_db | default('wso2_apim_shared_db') }}"
apim_shared_db_username: "{{ mysql_user | default('nemis') }}"
apim_shared_db_password: "{{ mysql_password | default('nemis1234') }}"

# Server settings
apim_server_hostname: "{{ apim_hostname | default('localhost') }}"
apim_server_base_path: "https://{{ apim_server_hostname }}"

# IS connection (for event listener)
apim_server_host: "{{ apim_host | default('localhost') }}"
apim_server_port: "{{ apim_port | default('9443') }}"
